name: React App Auto Deploy Flow(Tencent Axzure)
on: [push, pull_request]

jobs: 
  workingflow-job:
    name: react-app-workingflow
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Branch
      uses: actions/checkout@v3

    - name: Install and Build
      run: |
        npm install
        npm run build

    - name: Deploy To Tecent Axzure
      uses: srueda99/scp-action@v12
      with:
          token: ${{ secrets.ACTIONSECRET }}
          port: 22
          host: ${{ secrets.SERVER_HOST }}
          destination: "/home/${{ secrets.SERVER_FOLDER }}/"
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}