name: React App Auto Deploy Flow(Tencent Axzure)
on: [push, pull_request]

jobs: 
  workingflow-job:
    name: react-app-workingflow
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Branch
      uses: actions/checkout@v3

    - name: Install and Build
      run: |
        yarn
        yarn build

    - name: Deploy To Tecent Axzure
      uses: mdallasanta/ssh-scp-deploy@v1.2.0
      with:
          local: './build/**'
          remote: ${{ secrets.SERVER_FOLDER }}
          host: ${{ secrets.SERVER_HOST }}
          user: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}  
          port: 22

          